#! /bin/bash

DIRECTORYMOVIES=/run/media/tyler/data1/movies
DIRECTORYSHOWS=/run/media/tyler/data3/data/serien
DIRECTORYPICS=/run/media/tyler/data3/data/Bilder/canonixus
RETVAL=0

# kill minidlna if argument is k
killd(){
	if [ ! -f /home/tyler/.config/minidlna/minidlna.pid ]; then
		printf 'minidlna is not running!\n'
		exit 1
	fi
	printf 'Killing minidlna process\n'
	killall minidlnad
	RETVAL=0
}

# check if database has to be updated on argument r
update(){
	if [ ! -f "/home/tyler/.config/minidlna/minidlna.pid" ]; then
		printf 'minidlna is not running, starting the daemon...\n'
		minidlnad -f /home/tyler/.config/minidlna/minidlna.conf -P /home/tyler/.config/minidlna/minidlna.pid
	fi
	printf 'Updating database...\n'
	#rm /home/tyler/.config/minidlna/cache/files.db
	minidlnad -f /home/tyler/.config/minidlna/minidlna.conf -P /home/tyler/.config/minidlna/minidlna.pid
	STATUS=""
	STATUS_NEW=""
	while : ; do
		STATUS=$(curl -s  localhost:8200)
		sleep 1
		STATUS_NEW=$(curl -s localhost:8200)
		printf '*'
		[[ "$STATUS" != "$STATUS_NEW" ]] || break
	done
	printf '\nDatabase up to date. Daemon running.\n'
	RETVAL=0
}

show() {
	if [ ! -f "/home/tyler/.config/minidlna/minidlna.pid" ]; then
		printf 'minidlna is not running...\n'
	else
		printf 'minidlna is running.\n'
	fi

	if [ -d "$DIRECTORYMOVIES" ] || [ -d "$DIRECTORYSHOWS" ] || [ -d "$DIRECTORYPICS" ] ; then
		if [ -d "$DIRECTORYMOVIES" ]; then
			printf 'Found directory with movies.\n'
		fi
		if [ -d "$DIRECTORYSHOWS" ]; then
			printf 'Found directory with shows.\n'
		fi
		if [ -d "$DIRECTORYPICS" ]; then
			printf 'Found directory with pics.\n'
		fi
	else
		printf 'No Mediadirectories found! Exiting\n'
	fi
	RETVAL=0
}

run() {
	if [ -f "/home/tyler/.config/minidlna/minidlna.pid" ]; then
		printf 'minidlna is already running...\n'
		exit 0
	fi
	if [ ! -d "$DIRECTORYMOVIES" ] && [ ! -d "$DIRECTORYSHOWS" ] && [ ! -d "$DIRECTORYPICS" ] ; then
		printf 'No Mediadirectories found! Exiting\n'
		exit 1
	fi
	minidlnad -f /home/tyler/.config/minidlna/minidlna.conf -P /home/tyler/.config/minidlna/minidlna.pid
	RETVAL=0
}

f1() {
	printf 'Usage: dlna OPTION\n'
	printf '\t -r, --run run minidlnad daeomn\n'
	printf '\t -s, --show show available directories\n'
	printf '\t -k, --kill kill minidlna daemon\n'
	printf '\t -u, --update update database and run minidlna daemon if it is not already running\n'
	RETVAL=0
}

case "$1" in
	-s|--show)
		show
		;;
	-k|--kill)
		killd
		;;
	-u|--update)
		update
		;;
	-r|--run)
		run
		;;
	-h|--help)
		f1
		;;
	*)
		show
		printf '\nUse dlna -h oder dlna --help to get more info.\n'
esac

exit $REATVAL
