#!/bin/bash

# get sink
SINK=1
SINK=$(pamixer --list-sinks | grep Matisse | awk '{print $1}')
if [ $(pamixer --list-sinks | wc -l) -gt 2 ]; then
    pamixer --sink $SINK -m # mute headphones
    SINK=$(pamixer --list-sinks | grep TEAC | awk '{print $1}')
fi

# set volume
if [ "$1" == "low" ]; then
    pamixer --sink $SINK --unmute --decrease 5
elif [ "$1" == "high" ]; then
    pamixer --sink $SINK --unmute --increase 5
elif [ "$1" == "mute" ]; then
    pamixer --sink $SINK -t
else
    echo "Usage volume [low | high | mute]"
fi

# get appropriate icon
GETMUTE=$(pamixer --sink $SINK --get-mute)
if [ "$GETMUTE" == "false" ]; then
    # sink is on, get icon from volume value
    VALUE=$(pamixer --sink $SINK --get-volume)
    if [ "$VALUE" -eq 0 ]; then
        ICON="/usr/share/icons/Faenza-Dark/status/16/audio-volume-muted-panel.png"
    elif [ "$VALUE" -le 25 ]; then
        ICON="/usr/share/icons/Faenza-Dark/status/16/audio-volume-off.png"
    elif [ "$VALUE" -le 50 ]; then
        ICON="/usr/share/icons/Faenza-Dark/status/16/audio-volume-low.png"
    elif [ "$VALUE" -le 75 ]; then
        ICON="/usr/share/icons/Faenza-Dark/status/16/audio-volume-medium.png"
    else
        ICON="/usr/share/icons/Faenza-Dark/status/16/audio-volume-high.png"
    fi
else
    VALUE=off
    ICON="/usr/share/icons/Faenza-Dark/status/16/audio-volume-muted-blocked-panel.png"
fi

ID=$(cat ~/.i3/.dunst_vol)
if [ $ID -gt 0 ]; then
    dunstify -p -r $ID -i $ICON "Volume: $VALUE" >~/.i3/.dunst_vol
else
    dunstify -p -i $ICON "Volume: $VALUE" >~/.i3/.dunst_vol
fi

